name: smalltalkCI
on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        smalltalk:
          - Squeak64-5.3
          - Squeak64-5.2
          - Squeak64-5.1
          - Squeak64-trunk
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: hpi-swa/setup-smalltalkCI@v1
      id: smalltalkci
      with:
        smalltalk-version: ${{ matrix.smalltalk }}
    - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-version }}
      shell: bash
      timeout-minutes: 15
